// Shared industry and sector data for use across the app
// Source of truth copied from network.tsx

export const industries = [
  'Agriculture',
  'Automotive',
  'Construction',
  'Creative & Media',
  'Education & Training',
  'Energy & Environment',
  'Food & Beverage Services',
  'Government & Public Services',
  'Healthcare & Wellness',
  'Manufacturing & Industrial',
  'Professional & Financial Services',
  'Property Maintenance',
  'Retail & Consumer Goods',
  'Technology & Digital',
  'Transportation & Logistics',
  'Travel',
  'Venue'
];

export const sectorOptions: Record<string, string[]> = {
  Agriculture: [
    'Agricultural Equipment',
    'Agricultural Equipment Retail',
    'Agricultural Services',
    'Agricultural Supply',
    'Crop Nutrition/Protection',
    'Farming',
    'Farm Labor',
    'Farm Management',
    'Farm Supply',
    'Fertilizer',
    'Harvesting',
    'Irrigation Services/Supply',
    'Livestock',
    'Pesticides',
    'Veterinary Services/Supply',
    'Vineyards',
    'Agriculture Lab',
    'Field Trials',
    'Chemicals',
    'Dairy',
    'Dairy Services',
    'Agriculture Real Estate',
    'Crop Insurance',
    'Asset Management'
  ],
  Automotive: [
    'Automotive',
    'Automotive Rentals',
    'Automotive Retail',
    'Car Audio',
    'Car Wash',
    'Auto Detailing',
    'Battery Services',
    'Roadside',
    'Tire Services',
    'Tow Services',
    'Repossession Services'
  ],
  Construction: [
    'Commercial Construction',
    'Residential Construction',
    'Construction & Trades',
    'Specialized Trades',
    'Construction Aggregates'
  ],
  'Creative & Media': [
    'Audio Engineering',
    'Content Creation',
    'Design',
    'Film & Video',
    'Music Production',
    'Photography',
    'Writing & Publishing',
    'News, Current Events & Journalism'
  ],
  'Education & Training': [
    'Corporate Training',
    'Educational Services',
    'Formal Education',
    'Library',
    'University',
    'High School',
    'Junior College'
  ],
  'Energy & Environment': [
    'Analysis',
    'Energy',
    'Environment',
    'Utilities',
    'Water Services'
  ],
  'Food & Beverage Services': [
    'Bars & Nightlife',
    'Cafe',
    'Coffee Shops',
    'Food Services',
    'Restaurants'
  ],
  'Government & Public Services': [
    'Government',
    'Non-Profits',
    'Social Services'
  ],
  'Healthcare & Wellness': [
    'Dental Services',
    'Fitness',
    'Healthcare Providers',
    'Medical Devices',
    'Mental Health',
    'Nutrition',
    'Pharmaceuticals',
    'Physical Therapy',
    'Wellness'
  ],
  'Manufacturing & Industrial': [
    'Aerospace',
    'Chemicals',
    'Food & Beverage Manufacturing',
    'Hydraulic Services/Parts',
    'Industrial',
    'Textiles'
  ],
  'Professional & Financial Services': [
    'Accounting',
    'Architecture & Design',
    'Consulting',
    'Engineering',
    'Financial Services',
    'Legal Services',
    'Marketing & Advertising',
    'Real Estate',
    'Health Insurance',
    'Auto Insurance',
    'Home Insurance',
    'Asset Management',
    'Financial Management',
    'Financial Analysis',
    'Asset Protection',
    'Property Management'
  ],
  'Property Maintenance': [
    'Electrical',
    'Handy Man',
    'HVAC',
    'Landscaping',
    'Lawn Care',
    'Pressure Washing',
    'Waste Removal'
  ],
  'Retail & Consumer Goods': [
    'Apparel',
    'Beauty',
    'Bookstore',
    'Electronics',
    'Equipment Rentals',
    'Gardening',
    'Hardware',
    'Home Goods',
    'Specialty Retail',
    'Tools',
    'Western Wear',
    'Work Wear',
    'Barbershop',
    'Hair/Nail Salon',
    'Massage Parlor',
    'Spa',
    'Rentals',
    'Cosmetics',
    'General Products',
    'Parts Supply',
    'Arts & Crafts'
  ],
  'Technology & Digital': [
    'AI & Machine Learning',
    'Blockchain',
    'Cloud Computing',
    'Cybersecurity',
    'Data & Analytics',
    'E-commerce Platforms',
    'EdTech',
    'FinTech',
    'Gaming',
    'Hardware & Electronics',
    'HealthTech',
    'IT Services',
    'Software & SaaS',
    'Telecommunications',
    'Web Development'
  ],
  'Transportation & Logistics': [
    'Equipment Transportation',
    'Logistics',
    'Shipping',
    'Packaging Warehouse',
    'Cold Storage',
    'Storage Warehouse',
    'Mini Storage',
    'RV Storage',
    'Boat Storage'
  ],
  Travel: [
    'Accommodation',
    'Hospitality',
    'Air Travel',
    'Hotel',
    'RV Park',
    'Bus Transportation',
    'Train Transportation'
  ],
  Venue: [
    'Ballroom',
    'Convention Center',
    'Event Hall',
    'Private Venue',
    'Stadium'
  ]
};

export const getCategoryKey = (category: string): string => {
  const keyMap: { [key: string]: string } = {
    'Agriculture': 'agriculture',
    'Automotive': 'automotive',
    'Construction': 'construction',
    'Creative & Media': 'creativeMedia',
    'Education & Training': 'educationTraining',
    'Energy & Environment': 'energyEnvironment',
    'Food & Beverage Services': 'foodBeverageServices',
    'Government & Public Services': 'governmentPublicServices',
    'Healthcare & Wellness': 'healthcareWellness',
    'Manufacturing & Industrial': 'manufacturingIndustrial',
    'Professional & Financial Services': 'professionalFinancial',
    'Property Maintenance': 'propertyMaintenance',
    'Retail & Consumer Goods': 'retailConsumer',
    'Technology & Digital': 'technologyDigital',
    'Transportation & Logistics': 'transportationLogistics',
    'Travel': 'travel',
    'Venue': 'venue',
  };
  return keyMap[category] || category.toLowerCase().replace(/\s+|&/g, '').replace(/'/g, '');
};

export const getSpecialtyKey = (specialty: string): string => {
  const keyMap: { [key: string]: string } = {
    'Agricultural Equipment': 'agriculturalEquipment',
    'Agricultural Equipment Retail': 'agriculturalEquipmentRetail',
    'Agricultural Services': 'agriculturalServices',
    'Agricultural Supply': 'agriculturalSupply',
    'Crop Nutrition/Protection': 'cropNutritionProtection',
    'Farming': 'farming',
    'Farm Labor': 'farmLabor',
    'Farm Management': 'farmManagement',
    'Farm Supply': 'farmSupply',
    'Fertilizer': 'fertilizer',
    'Harvesting': 'harvesting',
    'Irrigation Services/Supply': 'irrigationServicesSupply',
    'Livestock': 'livestock',
    'Pesticides': 'pesticides',
    'Veterinary Services/Supply': 'veterinaryServicesSupply',
    'Vineyards': 'vineyards',
    'Agriculture Lab': 'agricultureLab',
    'Field Trials': 'fieldTrials',
    'Dairy': 'dairy',
    'Dairy Services': 'dairyServices',
    'Agriculture Real Estate': 'agricultureRealEstate',
    'Crop Insurance': 'cropInsurance',
    'Asset Management': 'assetManagement',
    'Audio Engineering': 'audioEngineering',
    'Content Creation': 'contentCreation',
    'Design': 'design',
    'Film & Video': 'filmVideo',
    'Music Production': 'musicProduction',
    'Photography': 'photography',
    'Writing & Publishing': 'writingPublishing',
    'News, Current Events & Journalism': 'newsCurrentEventsJournalism',
    'Commercial Construction': 'commercialConstruction',
    'Residential Construction': 'residentialConstruction',
    'Construction & Trades': 'constructionTrades',
    'Specialized Trades': 'specializedTrades',
    'Construction Aggregates': 'constructionAggregates',
    'Corporate Training': 'corporateTraining',
    'Educational Services': 'educationalServices',
    'Formal Education': 'formalEducation',
    'Government': 'government',
    'Library': 'library',
    'Non-Profits': 'nonProfits',
    'Social Services': 'socialServices',
    'University': 'university',
    'High School': 'highSchool',
    'Junior College': 'juniorCollege',
    'Analysis': 'analysis',
    'Energy': 'energy',
    'Environment': 'environment',
    'Utilities': 'utilities',
    'Water Services': 'waterServices',
    'Bars & Nightlife': 'barsNightlife',
    'Cafe': 'cafe',
    'Coffee Shops': 'coffeeShops',
    'Food Services': 'foodServices',
    'Restaurants': 'restaurants',
    'Barbershop': 'barbershop',
    'Dental Services': 'dentalServices',
    'Fitness': 'fitness',
    'Hair/Nail Salon': 'hairNailSalon',
    'Healthcare Providers': 'healthcareProviders',
    'Massage Parlor': 'massageParlor',
    'Medical Devices': 'medicalDevices',
    'Mental Health': 'mentalHealth',
    'Nutrition': 'nutrition',
    'Pharmaceuticals': 'pharmaceuticals',
    'Physical Therapy': 'physicalTherapy',
    'Spa': 'spa',
    'Wellness': 'wellness',
    'Aerospace': 'aerospace',
    'Automotive': 'automotive',
    'Chemicals': 'chemicals',
    'Food & Beverage Manufacturing': 'foodBeverageManufacturing',
    'Hydraulic Services/Parts': 'hydraulicServicesParts',
    'Industrial': 'industrial',
    'Textiles': 'textiles',
    'Accounting': 'accounting',
    'Architecture & Design': 'architectureDesign',
    'Consulting': 'consulting',
    'Engineering': 'engineering',
    'Financial Services': 'financialServices',
    'Legal Services': 'legalServices',
    'Marketing & Advertising': 'marketingAdvertising',
    'Real Estate': 'realEstate',
    'Health Insurance': 'healthInsurance',
    'Auto Insurance': 'autoInsurance',
    'Home Insurance': 'homeInsurance',
    'Financial Management': 'financialManagement',
    'Financial Analysis': 'financialAnalysis',
    'Asset Protection': 'assetProtection',
    'Property Management': 'propertyManagement',
    'Auto Detailing': 'autoDetailing',
    'Electrical': 'electrical',
    'Handy Man': 'handyMan',
    'HVAC': 'hvac',
    'Landscaping': 'landscaping',
    'Lawn Care': 'lawnCare',
    'Pressure Washing': 'pressureWashing',
    'Waste Removal': 'wasteRemoval',
    'Apparel': 'apparel',
    'Automotive Rentals': 'automotiveRentals',
    'Automotive Retail': 'automotiveRetail',
    'Beauty': 'beauty',
    'Bookstore': 'bookstore',
    'Car Audio': 'carAudio',
    'Car Wash': 'carWash',
    'Electronics': 'electronics',
    'Equipment Rentals': 'equipmentRental',
    'Gardening': 'gardening',
    'Hardware': 'hardware',
    'Home Goods': 'homeGoods',
    'Specialty Retail': 'specialtyRetail',
    'Tools': 'tools',
    'Western Wear': 'westernWear',
    'Work Wear': 'workWear',
    'AI & Machine Learning': 'aiMachineLearning',
    'Blockchain': 'blockchain',
    'Cloud Computing': 'cloudComputing',
    'Cybersecurity': 'cybersecurity',
    'Data & Analytics': 'dataAnalytics',
    'E-commerce Platforms': 'ecommercePlatforms',
    'EdTech': 'edtech',
    'FinTech': 'fintech',
    'Gaming': 'gaming',
    'Hardware & Electronics': 'hardwareElectronics',
    'HealthTech': 'healthtech',
    'IT Services': 'itServices',
    'Software & SaaS': 'softwareSaas',
    'Telecommunications': 'telecommunications',
    'Web Development': 'webDevelopment',
    'Battery Services': 'batteryServices',
    'Equipment Transportation': 'equipmentTransportation',
    'Logistics': 'logistics',
    'Roadside': 'roadside',
    'Shipping': 'shipping',
    'Tire Services': 'tireServices',
    'Tow Services': 'towServices',
    'Repossession Services': 'repossessionServices',
    'Accommodation': 'accommodation',
    'Hospitality': 'hospitality',
    'Air Travel': 'airTravel',
    'Hotel': 'hotel',
    'Packaging Warehouse': 'packagingWarehouse',
    'Cold Storage': 'coldStorage',
    'Storage Warehouse': 'storageWarehouse',
    'Mini Storage': 'miniStorage',
    'RV Storage': 'rvStorage',
    'Boat Storage': 'boatStorage',
    'RV Park': 'rvPark',
    'Bus Transportation': 'busTransportation',
    'Train Transportation': 'trainTransportation',
    'Rentals': 'rentals',
    'Cosmetics': 'cosmetics',
    'General Products': 'generalProducts',
    'Parts Supply': 'partsSupply',
    'Arts & Crafts': 'artsCrafts',
    'Ballroom': 'ballroom',
    'Convention Center': 'conventionCenter',
    'Event Hall': 'eventHall',
    'Private Venue': 'privateVenue',
    'Stadium': 'stadium',
  };

  return keyMap[specialty] || specialty.toLowerCase()
    .replace(/\s+|&|'/g, '')
    .replace(/\//g, '');
};
